Repository PingCAP-QE/ee-apps, pull requests merged in 2023-12, with the labels that each got.

#14 refactor(cloudevents-server): add `reason` filed
  cloudevents-server/client/main.go
  cloudevents-server/ent/client.go
  cloudevents-server/ent/migrate/schema.go
  cloudevents-server/ent/mutation.go
  cloudevents-server/ent/problemcaserun.go
  cloudevents-server/ent/problemcaserun/problemcaserun.go
  cloudevents-server/ent/problemcaserun/where.go
  cloudevents-server/ent/problemcaserun_create.go
  cloudevents-server/ent/problemcaserun_update.go
  cloudevents-server/ent/runtime.go
  cloudevents-server/ent/runtime/runtime.go
  cloudevents-server/ent/schema/problemcaserun.go
  cloudevents-server/pkg/events/custom/testcaserun/testcaserun.go
  cloudevents-server/pkg/events/custom/testcaserun/types.go
Labels: approved, size/XL

#32 feat(cloudevents-server): support notify taskrun and pipelinerun by lark bot app
  cloudevents-server/config.go
  cloudevents-server/configs/example-config-sqlite3.yaml
  cloudevents-server/configs/example-config.yaml
  cloudevents-server/go.mod
  cloudevents-server/go.sum
  cloudevents-server/main.go
  cloudevents-server/pkg/config/config.go
  cloudevents-server/pkg/events/custom/tekton/handler.go
  cloudevents-server/pkg/events/custom/tekton/handler_test.go
  cloudevents-server/pkg/events/custom/tekton/lark.go
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.failed.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.running.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.started.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.successful.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.unknown.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.failed.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.running.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.started.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.successful.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.unknown.json
  cloudevents-server/pkg/events/custom/tekton/types.go
  cloudevents-server/pkg/events/custom/testcaserun/handler.go
  cloudevents-server/pkg/events/custom/testcaserun/store.go
  cloudevents-server/pkg/events/custom/testcaserun/types.go
  cloudevents-server/pkg/events/handlers.go
Labels: size/XXL, approved

#34 opt(cloudevents-server): skip notify for task runs
  cloudevents-server/pkg/events/custom/tekton/handler.go
Labels: approved, size/S

#35 fix(tibuild): bump versions for golang and nodejs
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  OWNERS
  tibuild/Dockerfile
  tibuild/Makefile
  tibuild/api/api.go
  tibuild/cmd/branch_create_helper/main.go
  tibuild/cmd/tag_create_helper/main.go
  tibuild/cmd/tibuild/main.go
  tibuild/commons/database/mysql.go
  tibuild/deployments/docker/Dockerfile
  tibuild/go.mod
  tibuild/go.sum
  tibuild/gojenkins/artifact.go
  tibuild/gojenkins/jenkins.go
  tibuild/gojenkins/jenkins_test.go
  tibuild/gojenkins/job.go
  tibuild/gojenkins/label.go
  tibuild/gojenkins/pipeline.go
  tibuild/gojenkins/request.go
  tibuild/internalpkg/controller/params_available_for_pipeline.go
  tibuild/internalpkg/controller/pipeline_for_build_type.go
  tibuild/internalpkg/controller/pipeline_list_show.go
  tibuild/internalpkg/controller/pipeline_trigger.go
  tibuild/internalpkg/controller/request_result.go
  tibuild/internalpkg/controller/request_rotation.go
  tibuild/internalpkg/service/job_build.go
  tibuild/internalpkg/service/job_status.go
  tibuild/pkg/rest/controller/artifact_helper_handler.go
  tibuild/pkg/rest/controller/chat_print_server.go
  tibuild/pkg/rest/controller/common.go
  tibuild/pkg/rest/controller/dev_build_handler.go
  tibuild/pkg/rest/controller/hotfix_handler.go
  tibuild/pkg/rest/repo/dev_build_repo.go
  tibuild/pkg/rest/repo/dev_build_repo_test.go
  tibuild/pkg/rest/repo/eechat_head_creator.go
  tibuild/pkg/rest/repo/eechat_head_creator_test.go
  tibuild/pkg/rest/repo/github_head_creator.go
  tibuild/pkg/rest/repo/github_head_creator_test.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/jenkins.go
  tibuild/skaffold.yaml
  tibuild/website/package-lock.json
  tibuild/website/package.json
  tibuild/website/src/App.js
Labels: size/XXL, lgtm, approved

#39 Update Dockerfile
  tibuild/Dockerfile
Labels: approved, size/XS

#38 refactor(tibuild): rename `internalpkg` to `internal`
  tibuild/README.md
  tibuild/api/api.go
  tibuild/internal/controller/github_sso.go
  tibuild/internal/controller/params_available_for_pipeline.go
  tibuild/internal/controller/pipeline_for_build_type.go
  tibuild/internal/controller/pipeline_list_show.go
  tibuild/internal/controller/pipeline_trigger.go
  tibuild/internal/controller/request_result.go
  tibuild/internal/controller/request_rotation.go
  tibuild/internal/controller/test.go
  tibuild/internal/dto/testDTO.go
  tibuild/internal/entity/entities.go
  tibuild/internal/service/jenkins_init.go
  tibuild/internal/service/job_build.go
  tibuild/internal/service/job_status.go
Labels: approved, size/L

#53 feat(cloudevents-server): support sink events and produce for tibuild
  cloudevents-server/configs/example-config.yaml
  cloudevents-server/handlers.go
  cloudevents-server/main.go
  cloudevents-server/pkg/config/config.go
  cloudevents-server/pkg/events/custom/tekton/handler.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
  cloudevents-server/pkg/events/custom/tekton/handler_test.go
  cloudevents-server/pkg/events/custom/tibuild/handler.go
  cloudevents-server/pkg/events/custom/tibuild/types.go
  cloudevents-server/pkg/events/handler/handler.go
  cloudevents-server/pkg/events/handler/types.go
  cloudevents-server/pkg/events/handlers.go
Labels: size/XXL, approved

#55 feat: add basic auth to allow target
  tibuild/api/api.go
  tibuild/commons/configs/config.go
  tibuild/commons/configs/config_test.go
  tibuild/configs/config_example.yaml
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/pkg/rest/controller/common.go
  tibuild/pkg/rest/controller/dev_build_handler.go
  tibuild/pkg/rest/repo/dev_build_repo_test.go
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/error.go
  tibuild/pkg/rest/service/model.go
  tibuild/tbctl/tbctl.py
Labels: lgtm, approved, size/L

#56 feat(dl): implement DL(downloader) server
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .gitignore
  change-insight/go.mod
  change-insight/go.sum
  cloudevents-server/go.mod
  cloudevents-server/go.sum
  cloudevents-server/pkg/events/custom/testcaserun/test.sh
  dl/Dockerfile
  dl/README.md
  dl/cmd/server-cli/http.go
  dl/cmd/server-cli/main.go
  dl/cmd/server/http.go
  dl/cmd/server/main.go
  dl/design/design.go
  dl/gen/http/cli/server/cli.go
  dl/gen/http/ks3/client/cli.go
  dl/gen/http/ks3/client/client.go
  dl/gen/http/ks3/client/encode_decode.go
  dl/gen/http/ks3/client/paths.go
  dl/gen/http/ks3/client/types.go
  dl/gen/http/ks3/server/encode_decode.go
  dl/gen/http/ks3/server/paths.go
  dl/gen/http/ks3/server/server.go
  dl/gen/http/ks3/server/types.go
  dl/gen/http/oci/client/cli.go
  dl/gen/http/oci/client/client.go
  dl/gen/http/oci/client/encode_decode.go
  dl/gen/http/oci/client/paths.go
  dl/gen/http/oci/client/types.go
  dl/gen/http/oci/server/encode_decode.go
  dl/gen/http/oci/server/paths.go
  dl/gen/http/oci/server/server.go
  dl/gen/http/oci/server/types.go
  dl/gen/http/openapi.json
  dl/gen/http/openapi.yaml
  dl/gen/http/openapi3.json
  dl/gen/http/openapi3.yaml
  dl/gen/ks3/client.go
  dl/gen/ks3/endpoints.go
  dl/gen/ks3/service.go
  dl/gen/oci/client.go
  dl/gen/oci/endpoints.go
  dl/gen/oci/service.go
  dl/go.mod
  dl/go.sum
  dl/ks3.go
  dl/oci.go
  dl/pkg/ks3/cfg.go
  dl/pkg/oci/download.go
  dl/skaffold.yaml
  tibuild/Dockerfile
  tibuild/go.mod
  tibuild/go.sum
  tibuild/gojenkins/cli/jenkinsctl/go.mod
  tibuild/gojenkins/cli/jenkinsctl/go.sum
Labels: size/XXL, approved

#58 reafactor(cloud-events): just deal tekton pipelinerun final state events
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
Labels: approved, size/XS

#60 fix(dl): fix yaml config and get object logic
  dl/ks3.go
  dl/pkg/ks3/cfg.go
Labels: approved, size/M

#61 ci: fix chart release flow
  .github/workflows/charts-release.yaml
Labels: size/S

#63 fix(cloudevents): fix notify conditions
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
Labels: approved, size/S

#64 fix(cloudevents): fix UT cases
  cloudevents-server/pkg/config/config.go
  cloudevents-server/pkg/events/custom/tekton/handler.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
  cloudevents-server/pkg/events/custom/tekton/handler_test.go
  cloudevents-server/pkg/events/custom/tekton/lark.go
Labels: approved, size/L
