Repository PingCAP-QE/ee-apps, pull requests merged in 2024-01, with the labels that each got.

#68 fix(cloudevents): fix error for case run report
  cloudevents-server/configs/example-config-sqlite3.yaml
  cloudevents-server/ent/client.go
  cloudevents-server/ent/problemcaserun_update.go
  cloudevents-server/ent/runtime/runtime.go
  cloudevents-server/pkg/events/custom/testcaserun/handler.go
  cloudevents-server/pkg/events/custom/testcaserun/types.go
Labels: approved, size/L

#69 opt(cloudevents-server): opt notify card UI
  cloudevents-server/pkg/events/custom/tekton/lark.go
  cloudevents-server/pkg/events/custom/tekton/lark_templates/pipelinerun-notify.yaml.tmpl
Labels: approved, size/L

#70 feat(cloudevents-server): render lark message with template
  cloudevents-server/go.mod
  cloudevents-server/go.sum
  cloudevents-server/pkg/events/custom/tekton/lark.go
  cloudevents-server/pkg/events/custom/tekton/lark_templates/pipelinerun-notify.yaml.tmpl
  cloudevents-server/pkg/events/custom/tekton/lark_templates/tekton-run-notify.yaml.tmpl
  cloudevents-server/pkg/events/custom/tekton/testdata/event-pipelinerun.successful.json
  cloudevents-server/pkg/events/custom/tekton/testdata/event-taskrun.successful.json
  cloudevents-server/pkg/events/custom/tekton/types.go
Labels: size/XXL, approved

#71 feat: default release-x.y.z branch for enterprise-plugin in hotfix
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
Labels: lgtm, approved, size/S

#72 fix: some builder image may longer than 64 char
  tibuild/pkg/rest/service/model.go
Labels: lgtm, approved
