Repository PingCAP-QE/ee-apps, pull requests merged in 2024-02, with the labels that each got.

#73 fix(cloudevents-server): refactor results parts for tekton run notification message
  cloudevents-server/pkg/events/custom/tekton/lark.go
  cloudevents-server/pkg/events/custom/tekton/lark_templates/tekton-run-notify.yaml.tmpl
  cloudevents-server/pkg/events/custom/tekton/types.go
Labels: approved, size/S

#67 feat: support tekton via cloud event
  tibuild/Makefile
  tibuild/api/api.go
  tibuild/commons/configs/config.go
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/go.mod
  tibuild/go.sum
  tibuild/pkg/rest/controller/dev_build_handler.go
  tibuild/pkg/rest/repo/dev_build_repo.go
  tibuild/pkg/rest/repo/dev_build_repo_test.go
  tibuild/pkg/rest/service/cloud_event_client.go
  tibuild/pkg/rest/service/cloud_event_client_test.go
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/gh_client.go
  tibuild/pkg/rest/service/gh_client_test.go
  tibuild/pkg/rest/service/interface.go
  tibuild/pkg/rest/service/model.go
  tibuild/pkg/rest/service/trigger.http
  tibuild/pkg/webhook/handler/cloudevent_handler.go
  tibuild/pkg/webhook/handler/cloudevent_test.go
  tibuild/pkg/webhook/handler/cloudevent_test.http
  tibuild/pkg/webhook/handler/event.json
  tibuild/pkg/webhook/service/cloudevent.go
  tibuild/pkg/webhook/service/cloudevent_test.go
  tibuild/pkg/webhook/service/tekton_event.json
  tibuild/tbctl/tbctl.py
Labels: size/XXL, lgtm, approved

#74 fix: github require loggin to avoid rate limit
  tibuild/api/api.go
  tibuild/pkg/rest/controller/dev_build_handler.go
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/gh_client.go
  tibuild/pkg/rest/service/gh_client_test.go
  tibuild/pkg/webhook/service/tekton_event.json
  tibuild/tbctl/tbctl.py
Labels: lgtm, approved, size/M

#78 fix: tekton null status
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/webhook/handler/cloudevent_handler.go
  tibuild/pkg/webhook/service/cloudevent.go
Labels: approved, size/S

#79 feat(cloudevents-server): add extral message receiver from event context
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
Labels: approved, size/S

#81 refract: simplify tekton status
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/pkg/rest/repo/dev_build_repo_test.go
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/model.go
Labels: approved, size/M

#82 refract: rename orasfile to oci file
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/model.go
  tibuild/pkg/webhook/service/cloudevent.go
Labels: lgtm, approved, size/M

#85 fix: sha256sum for oci artifact
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/model.go
Labels: lgtm, approved, size/M

#86 feat(cloudevents-server): support set receivers by event types
  cloudevents-server/configs/example-config-sqlite3.yaml
  cloudevents-server/configs/example-config.yaml
  cloudevents-server/handlers.go
  cloudevents-server/pkg/config/config.go
  cloudevents-server/pkg/events/custom/tekton/handler.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun.go
  cloudevents-server/pkg/events/custom/tekton/handler_pipelinerun_test.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun.go
  cloudevents-server/pkg/events/custom/tekton/handler_taskrun_test.go
  cloudevents-server/pkg/events/custom/tekton/lark.go
  cloudevents-server/pkg/lark/client.go
Labels: approved, size/L

#87 ci: full clone and fetch tags for skaffold build
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: approved, size/XS

#88 chore: add labels in `OWNERS` files
  change-insight/OWNERS
  cloudevents-server/OWNERS
  tibuild/OWNERS
Labels: approved, size/XS

#84 fix: add `startAt` and `endAt` for Tekton runs
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/model.go
  tibuild/pkg/webhook/service/cloudevent.go
Labels: lgtm, approved, size/L

#91 fix: StartTime maybe nil
  tibuild/pkg/webhook/service/cloudevent.go
Labels: lgtm, approved, size/S, area/tibuild

#92 chore: change event log to info
  tibuild/pkg/webhook/service/cloudevent.go
Labels: approved, size/XS, area/tibuild
