Repository PingCAP-QE/ee-apps, pull requests merged in 2025-04, with the labels that each got.

#253 feat(tibuild): support single platform build
  tibuild/pkg/rest/service/cloud_event_client.go
  tibuild/pkg/rest/service/dev_build_service.go
  tibuild/pkg/rest/service/model.go
Labels: approved, size/S, area/tibuild

#254 feat(chatops-lark): update tibuild dependency and add platform option for devbuild
  chatops-lark/go.mod
  chatops-lark/go.sum
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/devbuild_trigger.go
  tibuild/pkg/rest/service/cloud_event_client.go
Labels: approved, size/S, area/tibuild

#258 chore(tibuild-v2): fix go mods
  experiments/tibuild-v2/go.mod
  experiments/tibuild-v2/go.sum
  experiments/tibuild-v2/pkg/impl/artifact_test.go
  experiments/tibuild-v2/pkg/impl/devbuild_transform.go
Labels: approved, size/XL

#251 feat(lark): add `/ask` command using OpenAI
  chatops-lark/README.md
  chatops-lark/go.mod
  chatops-lark/go.sum
  chatops-lark/pkg/events/handler/ask.go
  chatops-lark/pkg/events/handler/ask_mcp.go
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/root.go
Labels: approved, size/XL

#260 refactor(chatops-lark): refactor config management with structured types
  chatops-lark/README.md
  chatops-lark/cmd/server/main.go
  chatops-lark/config.yaml.example
  chatops-lark/pkg/audit/send.go
  chatops-lark/pkg/botinfo/client.go
  chatops-lark/pkg/botinfo/client_test.go
  chatops-lark/pkg/config/config.go
  chatops-lark/pkg/events/handler/ask.go
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/devbuild_poll.go
  chatops-lark/pkg/events/handler/devbuild_trigger.go
  chatops-lark/pkg/events/handler/func_lark.go
  chatops-lark/pkg/events/handler/root.go
  chatops-lark/pkg/events/handler/types.go
  chatops-lark/pkg/response/reply.go
Labels: size/XXL, approved

#261 fix(chatops-lark): update credential configuration and command registry
  chatops-lark/README.md
  chatops-lark/config.yaml.example
  chatops-lark/pkg/events/handler/root.go
Labels: lgtm, approved, size/S

#262 feat(chatops-lark): lark bot reply enhance
  chatops-lark/pkg/botinfo/client.go
  chatops-lark/pkg/botinfo/client_test.go
  chatops-lark/pkg/events/handler/func_lark.go
  chatops-lark/pkg/events/handler/root.go
  chatops-lark/pkg/response/reply.go
Labels: lgtm, approved, size/L

#265 fix(tibuild): fix experimental edition name to experiment
  tibuild/pkg/rest/service/dev_build_service_test.go
  tibuild/pkg/rest/service/model.go
Labels: approved, size/S, area/tibuild
