Repository PingCAP-QE/ee-apps, pull requests merged in 2025-02, with the labels that each got.

#223 feat(chatops-lark): init with devbuild
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  chatops-lark/cmd/server/main.go
  chatops-lark/go.mod
  chatops-lark/go.sum
  chatops-lark/pkg/audit/audit-card.yaml.tmpl
  chatops-lark/pkg/audit/send.go
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/devbuild_poll.go
  chatops-lark/pkg/events/handler/devbuild_trigger.go
  chatops-lark/pkg/events/handler/hotfix.go
  chatops-lark/pkg/events/handler/root.go
  chatops-lark/pkg/response/command-response.yaml.tmpl
  chatops-lark/pkg/response/send.go
  chatops-lark/skaffold.yaml
Labels: size/XXL, approved

#228 feat(chatops-lark): avoid handling for dup events
  chatops-lark/go.mod
  chatops-lark/go.sum
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/root.go
Labels: approved, size/L

#232 feat(devbuild): devbuild support newarch ticdc
  tibuild/docs/docs.go
  tibuild/docs/swagger.json
  tibuild/docs/swagger.yaml
  tibuild/internal/controller/pipeline_trigger.go
  tibuild/pkg/rest/service/model.go
Labels: lgtm, approved, size/S, area/tibuild

#233 fix(tibuild): fix src image checking regexp
  tibuild/Dockerfile
  tibuild/pkg/rest/service/artifact_helper.go
Labels: approved, size/S, area/tibuild

#234 feat(chatops-lark): add health checking
  chatops-lark/README.md
  chatops-lark/cmd/server/main.go
Labels: approved, size/M

#235 feat(charts): add helm chart for chatops-lark app
  .github/workflows/charts-release.yaml
  charts/chatops-lark/.helmignore
  charts/chatops-lark/Chart.yaml
  charts/chatops-lark/templates/NOTES.txt
  charts/chatops-lark/templates/_helpers.tpl
  charts/chatops-lark/templates/deployment.yaml
  charts/chatops-lark/templates/hpa.yaml
  charts/chatops-lark/templates/service.yaml
  charts/chatops-lark/templates/serviceaccount.yaml
  charts/chatops-lark/templates/tests/test-connection.yaml
  charts/chatops-lark/values.yaml
Labels: approved, size/XL

#236 fix(charts): fix chatops-lark deployment manifest templates
  charts/chatops-lark/Chart.yaml
  charts/chatops-lark/templates/NOTES.txt
  charts/chatops-lark/templates/deployment.yaml
Labels: approved, size/S

#237 fix(charts): fix helm test for chatops-lark
  charts/chatops-lark/Chart.yaml
  charts/chatops-lark/templates/tests/test-connection.yaml
Labels: approved, size/XS

#238 fix(chatops-lark): remove the dup response
  chatops-lark/pkg/events/handler/root.go
  chatops-lark/pkg/response/command-response.yaml.tmpl
Labels: approved, size/M

#240 feat(chatops-lark): support reply to group mention bot message
  chatops-lark/.gitignore
  chatops-lark/README.md
  chatops-lark/pkg/events/handler/root.go
Labels: lgtm, approved, size/L

#242 feat(chatops-lark): Enhance the user-friendliness of cmd prompts.
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/root.go
Labels: lgtm, approved, size/L

#243 chore(chatops-lark): remove some not used cmds
  chatops-lark/pkg/events/handler/cherrypick.go
  chatops-lark/pkg/events/handler/devbuild.go
  chatops-lark/pkg/events/handler/hotfix.go
  chatops-lark/pkg/events/handler/root.go
Labels: lgtm, approved, size/L
