Repository PingCAP-QE/ee-apps, pull requests merged in 2025-03, with the labels that each got.

#244 feat(experiments): init for tibuild-v2
  experiments/tibuild-v2/.gitignore
  experiments/tibuild-v2/README.md
  experiments/tibuild-v2/cmd/tibuild-cli/http.go
  experiments/tibuild-v2/cmd/tibuild-cli/main.go
  experiments/tibuild-v2/cmd/tibuild/http.go
  experiments/tibuild-v2/cmd/tibuild/init.go
  experiments/tibuild-v2/cmd/tibuild/main.go
  experiments/tibuild-v2/configs/config_example.yaml
  experiments/tibuild-v2/design/design.go
  experiments/tibuild-v2/gen/artifact/client.go
  experiments/tibuild-v2/gen/artifact/endpoints.go
  experiments/tibuild-v2/gen/artifact/service.go
  experiments/tibuild-v2/gen/devbuild/client.go
  experiments/tibuild-v2/gen/devbuild/endpoints.go
  experiments/tibuild-v2/gen/devbuild/service.go
  experiments/tibuild-v2/gen/http/artifact/client/cli.go
  experiments/tibuild-v2/gen/http/artifact/client/client.go
  experiments/tibuild-v2/gen/http/artifact/client/encode_decode.go
  experiments/tibuild-v2/gen/http/artifact/client/paths.go
  experiments/tibuild-v2/gen/http/artifact/client/types.go
  experiments/tibuild-v2/gen/http/artifact/server/encode_decode.go
  experiments/tibuild-v2/gen/http/artifact/server/paths.go
  experiments/tibuild-v2/gen/http/artifact/server/server.go
  experiments/tibuild-v2/gen/http/artifact/server/types.go
  experiments/tibuild-v2/gen/http/cli/tibuild/cli.go
  experiments/tibuild-v2/gen/http/devbuild/client/cli.go
  experiments/tibuild-v2/gen/http/devbuild/client/client.go
  experiments/tibuild-v2/gen/http/devbuild/client/encode_decode.go
  experiments/tibuild-v2/gen/http/devbuild/client/paths.go
  experiments/tibuild-v2/gen/http/devbuild/client/types.go
  experiments/tibuild-v2/gen/http/devbuild/server/encode_decode.go
  experiments/tibuild-v2/gen/http/devbuild/server/paths.go
  experiments/tibuild-v2/gen/http/devbuild/server/server.go
  experiments/tibuild-v2/gen/http/devbuild/server/types.go
  experiments/tibuild-v2/gen/http/openapi.json
  experiments/tibuild-v2/gen/http/openapi.yaml
  experiments/tibuild-v2/gen/http/openapi3.json
  experiments/tibuild-v2/gen/http/openapi3.yaml
  experiments/tibuild-v2/go.mod
  experiments/tibuild-v2/go.sum
  experiments/tibuild-v2/pkg/config/config.go
  experiments/tibuild-v2/pkg/impl/artifact.go
  experiments/tibuild-v2/pkg/impl/devbuild.go
  experiments/tibuild-v2/skaffold.yaml
Labels: size/XXL, approved

#245 feat(chatops-lark): get bot name from api
  chatops-lark/README.md
  chatops-lark/cmd/server/main.go
  chatops-lark/pkg/botinfo/client.go
  chatops-lark/pkg/botinfo/client_test.go
  chatops-lark/pkg/events/handler/root.go
Labels: size/XXL, lgtm, approved

#246 feat(insight): add ci job crawler
  insight/README.md
  insight/crawlers/ci/prow-jobs.test.ts
  insight/crawlers/ci/prow-jobs.ts
Labels: approved, size/XL

#248 fix(pubisher): support beta and rc GA tags
  publisher/pkg/impl/funcs_tiup.go
  publisher/pkg/impl/funcs_tiup_test.go
Labels: lgtm, approved, size/S

#249 refactor(tibuild): tibuild-v2
  .github/workflows/ci.yaml
  experiments/tibuild-v2/cmd/tibuild/init.go
  experiments/tibuild-v2/cmd/tibuild/main.go
  experiments/tibuild-v2/go.mod
  experiments/tibuild-v2/go.sum
  experiments/tibuild-v2/internal/database/ent/devbuild.go
  experiments/tibuild-v2/internal/database/ent/devbuild/devbuild.go
  experiments/tibuild-v2/internal/database/ent/devbuild/where.go
  experiments/tibuild-v2/internal/database/ent/devbuild_create.go
  experiments/tibuild-v2/internal/database/ent/devbuild_update.go
  experiments/tibuild-v2/internal/database/ent/migrate/schema.go
  experiments/tibuild-v2/internal/database/ent/mutation.go
  experiments/tibuild-v2/internal/database/ent/runtime.go
  experiments/tibuild-v2/internal/database/schema/devbuild.go
  experiments/tibuild-v2/internal/service/design/design.go
  experiments/tibuild-v2/internal/service/gen/devbuild/client.go
  experiments/tibuild-v2/internal/service/gen/devbuild/endpoints.go
  experiments/tibuild-v2/internal/service/gen/devbuild/service.go
  experiments/tibuild-v2/internal/service/gen/http/artifact/client/cli.go
  experiments/tibuild-v2/internal/service/gen/http/cli/tibuild/cli.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/client/cli.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/client/client.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/client/encode_decode.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/client/paths.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/client/types.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/server/encode_decode.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/server/paths.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/server/server.go
  experiments/tibuild-v2/internal/service/gen/http/devbuild/server/types.go
  experiments/tibuild-v2/internal/service/gen/http/openapi.json
  experiments/tibuild-v2/internal/service/gen/http/openapi.yaml
  experiments/tibuild-v2/internal/service/gen/http/openapi3.json
  experiments/tibuild-v2/internal/service/gen/http/openapi3.yaml
  experiments/tibuild-v2/internal/service/impl/artifact.go
  experiments/tibuild-v2/internal/service/impl/devbuild.go
  experiments/tibuild-v2/internal/service/impl/devbuild_create.go
  experiments/tibuild-v2/internal/service/impl/devbuild_github.go
  experiments/tibuild-v2/internal/service/impl/devbuild_jenkins.go
  experiments/tibuild-v2/internal/service/impl/devbuild_sync.go
  experiments/tibuild-v2/internal/service/impl/devbuild_tekton.go
  experiments/tibuild-v2/internal/service/impl/devbuild_transform.go
  experiments/tibuild-v2/internal/service/tests/artifact_test.go
  experiments/tibuild-v2/internal/service/tests/devbuild_test.go
  experiments/tibuild-v2/pkg/config/config.go
  experiments/tibuild-v2/skaffold.yaml
Labels: size/XXL, approved
